In [35]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn import linear_model

In [44]:
df = pd.read_csv('hiring.csv')

In [45]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [38]:
#Salary is the dependent variable, experience , test_score and interview_score are the independent variables

In [55]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0      zeros                    8.0                           9      50000
1      zeros                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [65]:
df=df.rename(columns={"test_score(out of 10)":"test_score","interview_score(out of 10)":"interview_score","salary($)":"salary"})

In [66]:
df

experience  test_score  interview_score  salary
0      zeros         8.0                9   50000
1      zeros         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [61]:
df.test_score = df.test_score.fillna(df.test_score.median())

In [73]:
a=np.array([0,0,5,2,7,3,10,11])
df.experience = a.transpose()
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [75]:
df.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score, dtype: float64

In [76]:
reg= linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression()

In [77]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [78]:
reg.intercept_

17737.26346433768

In [79]:
#salary = 2812*experience + 1845*test_score + 2205*inteview_score + 17737 

In [80]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [81]:
reg.predict([[12,10,10]])

array([92002.18340611])